project_name: intrvl-r
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  binary: intrvl-r

  goos:
    - windows
    - darwin
    - linux
    - freebsd
    - openbsd
    - netbsd
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  ignore:
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: freebsd
      goarch: arm64
    - goos: openbsd
      goarch: arm
      goarm: 6
  # hooks:
    # Please install upx first, https://github.com/upx/upx/releases
    # post: compress.bat
    # post: ./compress.sh
env_files:
  github_token: ./github_token
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^tests'
      - Merge pull request
      - Merge branch
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - none*
  wrap_in_directory: false
release:
  draft: true
